# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zwTH13TFT7TfqY8tFLM3RW0vGOCUBKbk
"""



"""# Task
Build, train, and evaluate a Convolutional Neural Network (CNN) for handwritten digit recognition using the MNIST dataset, and create a function to predict digits from uploaded image files.

## Load and Preprocess MNIST Dataset

### Subtask:
Load the MNIST dataset, normalize pixel values, reshape images for CNN input, and encode labels.

**Reasoning**:
The first step is to import the necessary libraries, load the MNIST dataset, reshape the images for CNN input, normalize pixel values, and one-hot encode the labels as per the instructions.
"""

import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# 1. Load the MNIST training and test data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# 2. Reshape the X_train and X_test datasets
# Images are 28x28, so we reshape to (num_samples, 28, 28, 1) for CNN input
X_train = X_train.reshape((X_train.shape[0], 28, 28, 1)).astype('float32')
X_test = X_test.reshape((X_test.shape[0], 28, 28, 1)).astype('float32')

# 3. Convert pixel values to float32 and normalize them
X_train = X_train / 255.0
X_test = X_test / 255.0

# 4. One-hot encode the y_train and y_test labels
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

print("MNIST dataset loaded and preprocessed:")
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

"""## Build the CNN Model

### Subtask:
Define the architecture of the Convolutional Neural Network using Keras, including convolutional layers, pooling layers, and dense layers.

**Reasoning**:
I need to define the CNN model architecture as specified in the instructions, including importing the necessary Keras layers, adding convolutional, pooling, flatten, dense, and dropout layers, and then printing the model summary.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# 1. Initialize a Sequential model
model = Sequential([
    # 2. Add a Conv2D layer
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    # 3. Add a MaxPooling2D layer
    MaxPooling2D((2, 2)),
    # 4. Add another Conv2D layer
    Conv2D(64, (3, 3), activation='relu'),
    # 5. Add another MaxPooling2D layer
    MaxPooling2D((2, 2)),
    # 6. Flatten the output
    Flatten(),
    # 7. Add a Dense layer
    Dense(128, activation='relu'),
    # 8. Add a Dropout layer
    Dropout(0.5),
    # 9. Add the final Dense output layer
    Dense(10, activation='softmax')
])

# Print the model summary
model.summary()

"""**Reasoning**:
The next logical step after defining the model architecture is to compile the model. This involves specifying the optimizer, loss function, and metrics for training.


"""

from tensorflow.keras.optimizers import Adam

# 1. Compile the model
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("Model compiled successfully with Adam optimizer, categorical_crossentropy loss, and accuracy metric.")

"""## Compile and Train the Model

### Subtask:
Train the CNN model using the preprocessed MNIST training data and validate it with the test data.

**Reasoning**:
I need to train the model using the specified training and validation data, epochs, and batch size, and store the training history as instructed.
"""

print("Training the model...")
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=10,
    batch_size=32,
    verbose=1
)

print("Model training complete. Training history stored in 'history' variable.")
# Save the trained model
model.save("saved_model/mnist_cnn_model.h5")
print("Model saved successfully!")
